- name: 上传docker镜像
  copy:
    src: "{{ item }}"
    dest: "/tmp/ansible/images/"
  loop:
    - "files/images/pause-amd64_3.1.tgz"
    - "files/images/kube-proxy-amd64_v1.10.1.tgz"
  register: imgs

- name: 装载docker镜像
  shell: "docker load -i {{ item }}"
  loop: "{{ imgs.results | map(attribute='dest') | list }}"

- name: 初始化worker
  script: worker_setup.sh
  args:
    executable: /bin/bash

# - name: 清理临时文件
#   file:
#     path: "{{ item }}"
#     state: absent
#   loop:
#     - "/tmp/ansible"
